include:
    - path: compose.postgres.yaml

name: metro-now

services:
    backend:
        container_name: backend
        depends_on:
            - postgres
        build:
            context: .
        command:
            - /bin/bash
            - -c
            - |
                pnpm prisma:push
                pnpm start:prod

        restart: always
        ports:
            - 3001:3001
        volumes:
            - backend-data:/app
        env_file:
            - ".env.docker"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://host.docker.internal:3001/"]
            interval: 30s
            timeout: 10s
            retries: 5

volumes:
    backend-data:
