language: "en"
early_access: false
reviews:
    high_level_summary: false
    poem: false
    review_status: false
    collapse_walkthrough: true
    auto_review:
        auto_incremental_review: true
        enabled: true
        ignore_title_keywords:
            - "WIP"
            - "DO NOT MERGE"
        drafts: false
        base_branches:
            - "main"
chat:
    auto_reply: true
