name: metro-now

services:
    web:
        image: metro-now_web
        container_name: web
        pull_policy: build
        restart: always
        ports:
            - 3000:3000
        build:
            context: .
            dockerfile: ./Dockerfile
            no_cache: true
            target: metro-now_web

        healthcheck:
            test: ["CMD", "curl", "-f", "http://host.docker.internal:3000/"]
            interval: 30s
            timeout: 5s
            retries: 5

    postgres:
        container_name: postgres
        image: postgres:16-alpine
        restart: always
        ports:
            - 5432:${POSTGRES_PORT:-5432}
        volumes:
            - postgres-data:/var/lib/postgresql/data/
        env_file:
            - ".env.docker"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    backend:
        image: metro-now_backend
        container_name: backend
        pull_policy: build
        command:
            - /bin/bash
            - -c
            - |
                pnpm prisma:migrate:deploy
                pnpm start:prod
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: ./Dockerfile
            no_cache: true
            target: metro-now_backend

        restart: always
        ports:
            - 3001:3001
        volumes:
            - backend-data:/app
        env_file:
            - ".env.docker"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://host.docker.internal:3001/"]
            interval: 30s
            start_period: 300s
            timeout: 10s
            retries: 5

volumes:
    backend-data:
    postgres-data:
