name: Backend

on: push

jobs:
    ci:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - uses: pnpm/action-setup@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: |
                  pnpm install --frozen-lockfile

            - name: Build
              run: |
                  pnpm turbo run build --filter=@metro-now/backend

            - name: Test
              run: |
                  pnpm turbo run test --filter=@metro-now/backend

            - name: Lint
              run: |
                  pnpm turbo run lint --filter=@metro-now/backend

            - name: Types check
              run: |
                  pnpm turbo run types:check --filter=@metro-now/backend

    e2e:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: postgres_user
                    POSTGRES_PASSWORD: postgres_password
                    POSTGRES_DB: metro-now
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

            redis:
                image: redis
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 6379:6379

        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - uses: pnpm/action-setup@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: |
                  pnpm install --frozen-lockfile

            - name: Setup environment
              run: |
                  cd apps/backend
                  tail -n +3 ".env.local.example" > ".env.local"
                  echo "\n" >> ".env.local"
                  echo "GOLEMIO_API_KEY=${{ secrets.GOLEMIO_API_KEY }}" >> ".env.local"

                  echo "----- .env.local -----"
                  cat ".env.local"
                  echo "----------------------"

            - name: Run migrations
              run: |
                  pnpm turbo run migrate:deploy --filter=@metro-now/database

            - name: Run seeds
              run: |
                  pnpm turbo run seed --filter=@metro-now/database

            - name: Test e2e
              run: |
                  pnpm turbo run test:e2e --filter=@metro-now/backend
