name: Check format

on: push

jobs:
    format-check:
        name: Format check 💅
        runs-on: macos-latest

        steps:
            - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
              with:
                  swift-version: 5.10
            - uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - uses: pnpm/action-setup@v3

            - name: Check JS format
              run: |
                  pnpm install
                  pnpm format:check
