name: Docker

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - uses: docker/setup-buildx-action@v2
            - uses: docker/build-push-action@v4
              with:
                  context: .
                  file: "Dockerfile"
                  tags: metro-now:latest
                  load: true
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  push: false
