name: Mobile

on:
    push:
    pull_request:
    workflow_dispatch:

concurrency:
    group: mobile-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    swiftformat:
        runs-on: macos-latest
        timeout-minutes: 20

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install SwiftFormat
              run: brew install swiftformat

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Check mobile formatting
              run: pnpm app:format:check
