name: Web

on: push

jobs:
    ci:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - uses: pnpm/action-setup@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: |
                  pnpm install --frozen-lockfile

            - name: Build
              run: |
                  pnpm turbo run build --filter=@metro-now/web

            - name: Lint
              run: |
                  pnpm turbo run lint --filter=@metro-now/web

            - name: Types check
              run: |
                  pnpm turbo run types:check --filter=@metro-now/web
